ui:
  width: {{ .Env.SCREEN_WIDTH }}
  height: {{ .Env.SCREEN_HEIGHT }}
modules:
  - name: simple-clock
    url: https://github.com/glasslabs/clock/releases/download/v1.0.0/clock.wasm
    position: top:right